// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AkhiriQuizModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Finish Confirmation Modal --><template x-if=\"showFinishModal\"><div class=\"finish-modal-overlay\" @click.self=\"closeFinishModal()\"><div class=\"finish-modal-card\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"finish-modal-title\"><div class=\"finish-modal-icon\"><svg width=\"28\" height=\"28\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#F5821F\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle> <line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"13\"></line> <line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"></line></svg></div><h3 id=\"finish-modal-title\" class=\"finish-modal-title\">Akhiri Tes?</h3><p class=\"finish-modal-desc\">Apakah Anda yakin ingin mengakhiri tes?<br>Soal yang belum dijawab akan dianggap kosong.</p><div class=\"finish-modal-stats\"><div class=\"finish-modal-stat finish-modal-stat-answered\"><span class=\"finish-modal-stat-label\">Dijawab</span> <span class=\"finish-modal-stat-value\" x-text=\"answeredCount\"></span></div><div class=\"finish-modal-stat-divider\"></div><div class=\"finish-modal-stat finish-modal-stat-unanswered\"><span class=\"finish-modal-stat-label\">Belum Dijawab</span> <span class=\"finish-modal-stat-value\" x-text=\"unansweredCount\"></span></div></div><div class=\"finish-modal-actions\"><button type=\"button\" class=\"finish-modal-btn finish-modal-btn-secondary\" @click=\"closeFinishModal()\">Lanjut Mengerjakan</button> <button type=\"button\" class=\"finish-modal-btn finish-modal-btn-primary\" @click=\"confirmFinishQuiz()\" :disabled=\"isFinishing\">Akhiri Tes</button></div></div></div></template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
