// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer\" role=\"contentinfo\"><div class=\"footer-bg-symbol\" aria-hidden=\"true\">⌘</div><div class=\"container footer-inner\"><div class=\"footer-grid\"><!-- Logo + tagline --><div class=\"footer-brand\"><a href=\"/\" class=\"footer-logo\"><span class=\"footer-logo-icon\" aria-hidden=\"true\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 4a4 4 0 0 1 3.5 2\"></path><path d=\"M12 8a2 2 0 0 1 1.5 1\"></path><path d=\"M12 14a7 7 0 0 1-7-7\"></path><path d=\"M12 20a4 4 0 0 1-4-4\"></path><path d=\"M12 20a4 4 0 0 0 4-4\"></path><path d=\"M12 14c2 0 4-1.5 4-4.5\"></path><path d=\"M12 14c-2 0-4-1.5-4-4.5\"></path></svg></span> IQ Test</a><p class=\"footer-tagline\">Ukur kemampuan kognitifmu melalui tes IQ bergambar 20 soal yang reflektif dan ilmiah.</p></div><!-- Navigasi --><div><p class=\"footer-heading\">Navigasi</p><ul class=\"footer-links\"><li><a href=\"/\" class=\"footer-link\">Beranda</a></li><li><a href=\"/#features\" class=\"footer-link\">Fitur</a></li><li><a href=\"/quiz\" class=\"footer-link\">Mulai Tes</a></li></ul></div><!-- Informasi --><div><p class=\"footer-heading\">Informasi</p><ul class=\"footer-links\"><li><a href=\"#\" class=\"footer-link\">Privasi</a></li><li><a href=\"#\" class=\"footer-link\">Syarat & Ketentuan</a></li><li><a href=\"#\" class=\"footer-link\">Kontak</a></li></ul></div><!-- Sumber Daya --><div><p class=\"footer-heading\">Sumber Daya</p><ul class=\"footer-links\"><li><a href=\"#\" class=\"footer-link\">Dokumentasi</a></li><li><a href=\"#\" class=\"footer-link\">API</a></li><li><a href=\"#\" class=\"footer-link\">Blog</a></li></ul></div></div><!-- Copyright line --><div class=\"footer-copyright\"><p>&copy; 2026 IQ Test. All rights reserved.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
